"""DATAONE-WF-005 — MO Operation Types and work-order generation: fixtures.

Read from the real v19 source before anything here was written
(AUTOMATION_CONVENTIONS hard rule 6), in ``project-addons/dto_mrp/models/``:

* ``mrp.operation.type`` — ``name``, ``operation_type_line_ids``,
  ``mrp_production_ids``, ``mrp_production_ids_count``, and the delete guard
  ``_unlink_except_running_mo``            (mrp_operation_type.py:9-29)
* ``mrp.operation.type.line`` — ``sequence``, ``name``, ``workcenter_id``
  (required), ``mrp_operation_type_id``    (mrp_operation_type_line.py:13-16)
* ``mrp.production.mrp_operation_type_id`` (mrp_production.py:27)
* ``mrp.workorder`` — ``mrp_operation_type_id``,
  ``mrp_operation_type_line_id``, ``operation_type_line_sequence``
                                            (mrp_workorder.py:10-12)

**Work orders are generated by a COMPUTE, not by an onchange or a button.**
``_compute_workorder_ids`` (mrp_production.py:52) is decorated
``@api.depends('mrp_operation_type_id.operation_type_line_ids', ...)`` and
opens with::

    super()._compute_workorder_ids()
    for production in self:
        if production.state not in ('draft', 'confirmed'):
            continue

Two consequences the cases below rely on, and neither is assumed:

1. Writing ``mrp_operation_type_id`` is enough — no button call is needed,
   and the rows appear on the next read of ``workorder_ids``.
2. The override is inert past ``confirmed``. TC105 asserts exactly that: an
   RPC write on a ``progress`` MO changes no routing, so the field being
   readonly in the form is a second lock rather than the only one.

The delete-guard message TC104 requires verbatim, from
mrp_operation_type.py:29::

    'You can not delete the MO Operation Type if it is linked to the
     Manufacturing Order.'
"""
from __future__ import annotations

import uuid

from adapters.base import OdooRPCError
from framework.fg_common import m2o_id, make_trace  # noqa: F401 — re-exported
from framework.qa_fixtures import sweep_model, with_categ

WORKFLOW = "DATAONE-WF-005"
WORKFLOW_NAME = "Manufacturing Order Planning & Work-Order Generation"

trace = make_trace(WORKFLOW)

MARKER = "WF005"
_TOKEN = f"{MARKER}-{uuid.uuid4().hex[:8].upper()}"

#: Exact, from mrp_operation_type.py:29. TC104 forbids paraphrasing it.
ERROR_LINKED_MO = ("You can not delete the MO Operation Type if it is linked "
                   "to the Manufacturing Order.")


def tag(name: str) -> str:
    return f"{_TOKEN} {name}"


def fixture_token() -> str:
    return _TOKEN


# --------------------------------------------------------------- preconditions
def require_operation_types(ctx):
    """BLOCK unless dto_mrp contributed the operation-type layer."""
    rpc = ctx.adapter.rpc
    missing = [m for m in ("mrp.operation.type", "mrp.operation.type.line")
               if not rpc.model_exists(m)]
    missing += [f"mrp.production.{f}" for f in ("mrp_operation_type_id",)
                if not rpc.field_exists("mrp.production", f)]
    missing += [f"mrp.workorder.{f}" for f in
                ("mrp_operation_type_id", "mrp_operation_type_line_id",
                 "operation_type_line_sequence")
                if not rpc.field_exists("mrp.workorder", f)]
    if missing:
        ctx.blocked(
            f"dto_mrp is not contributing MO Operation Types to {ctx.env.key} "
            f"(db={ctx.env.db}) — missing: {', '.join(missing)}. Stage 3 must "
            f"be installed (tools/uat_cleanup.sh) first.")


# ------------------------------------------------------------------- sweeping
def sweep_wf005(rpc):
    """Best-effort teardown, children before parents."""
    for mo_id in rpc.search("mrp.production", [("name", "like", MARKER)]):
        for method in ("action_cancel",):
            try:
                rpc.call("mrp.production", method, [mo_id])
            except OdooRPCError:
                pass
    sweep_model(rpc, "mrp.production", [("name", "like", MARKER)])
    sweep_model(rpc, "mrp.operation.type.line",
                [("mrp_operation_type_id.name", "like", MARKER)])
    sweep_model(rpc, "mrp.operation.type", [("name", "like", MARKER)])
    sweep_model(rpc, "mrp.bom", [("code", "like", MARKER)])
    sweep_model(rpc, "mrp.workcenter", [("name", "like", MARKER)])
    sweep_model(rpc, "product.product", [("default_code", "like", MARKER)])
    sweep_model(rpc, "product.template", [("default_code", "like", MARKER)])


def open_namespace(ctx):
    with ctx.step(f"Sweep previous {MARKER} fixtures and open a fresh namespace"):
        sweep_wf005(ctx.adapter.rpc)
        ctx.log(f"fixture token = {_TOKEN}")


# ------------------------------------------------------------------- fixtures
def make_workcenter(rpc, label: str) -> int:
    return rpc.create("mrp.workcenter", {"name": tag(label)})


def make_operation_type(rpc, label: str,
                        lines: list[tuple[str, int, int]]) -> int:
    """lines = [(operation_name, workcenter_id, sequence), ...]."""
    return rpc.create("mrp.operation.type", {
        "name": tag(label),
        "operation_type_line_ids": [
            (0, 0, {"name": name, "workcenter_id": wc, "sequence": seq})
            for name, wc, seq in lines],
    })


def operation_lines(rpc, op_type_id: int) -> list[dict]:
    return rpc.search_read(
        "mrp.operation.type.line",
        [("mrp_operation_type_id", "=", op_type_id)],
        ["name", "workcenter_id", "sequence"], order="sequence, id")


def make_product(rpc, label: str) -> int:
    values = {
        "name": tag(label),
        "default_code": f"{_TOKEN}-{label}",
        "type": "consu",
    }
    if rpc.field_exists("product.template", "is_storable"):
        values["is_storable"] = True
    else:
        values["type"] = "product"
    return rpc.create("product.product", with_categ(rpc, values))


def product_tmpl_of(rpc, product_id: int) -> int:
    return m2o_id(rpc.read("product.product", [product_id],
                           ["product_tmpl_id"])[0]["product_tmpl_id"])


def make_bom(rpc, finished_id: int, component_id: int,
             operations: list[tuple[str, int]] | None = None) -> int:
    """A BoM, optionally carrying core's own routing operations.

    ``operations`` exists for TC105: with no MO Operation Type set, core's
    BoM-driven routing must survive untouched, and that can only be observed
    on a BoM that actually has operations.
    """
    values = {
        "product_tmpl_id": product_tmpl_of(rpc, finished_id),
        "code": tag("BOM"),
        "product_qty": 1.0,
        "type": "normal",
        "bom_line_ids": [(0, 0, {"product_id": component_id, "product_qty": 1.0})],
    }
    if operations:
        values["operation_ids"] = [
            (0, 0, {"name": name, "workcenter_id": wc})
            for name, wc in operations]
    return rpc.create("mrp.bom", values)


_MO_SEQ = {"n": 0}


def make_mo(rpc, finished_id: int, bom_id: int, qty: float = 1.0,
            op_type_id: int | None = None, confirm: bool = False) -> int:
    # mrp.production.name carries a "Reference must be unique per Company!"
    # constraint, so several MOs inside one case need distinct names. A
    # per-process counter keeps them readable and still inside the marker.
    _MO_SEQ["n"] += 1
    values = {
        "product_id": finished_id,
        "product_tmpl_id": product_tmpl_of(rpc, finished_id),
        "bom_id": bom_id,
        "product_qty": qty,
        "name": tag(f"MO-{_MO_SEQ['n']:03d}"),
    }
    if op_type_id is not None:
        values["mrp_operation_type_id"] = op_type_id
    mo_id = rpc.create("mrp.production", values)
    if confirm:
        rpc.call("mrp.production", "action_confirm", [mo_id])
    return mo_id


def workorders(rpc, mo_id: int) -> list[dict]:
    """The MO's work orders in operation-type line order.

    Ordered by ``operation_type_line_sequence`` first — that is the order the
    workbook asserts — then by id so the ordering is total even for rows core
    generated, which carry sequence 0.
    """
    return rpc.search_read(
        "mrp.workorder", [("production_id", "=", mo_id)],
        ["name", "workcenter_id", "state", "mrp_operation_type_id",
         "mrp_operation_type_line_id", "operation_type_line_sequence"],
        order="operation_type_line_sequence, id")


def workorder_ids(rpc, mo_id: int) -> list[int]:
    return [w["id"] for w in workorders(rpc, mo_id)]


def still_exists(rpc, model: str, ids: list[int]) -> list[int]:
    """Which of `ids` still exist — TC102 step 9 asserts this is empty."""
    if not ids:
        return []
    return rpc.search(model, [("id", "in", ids)])
